from .tool_calling import PROMPT_TEMPLATES as TOOL_CALLING_PROMPT_TEMPLATES
from .finagent import PROMPT_TEMPLATES as FINAGENT_PROMPT_TEMPLATES
from .simple_chat import PROMPT_TEMPLATES as SIMPLE_CHAT_PROMPT_TEMPLATES
from .debate_chat import PROMPT_TEMPLATES as DEBATE_CHAT_PROMPT_TEMPLATES
from .trading_offline import PROMPT_TEMPLATES as TRADING_OFFLINE_PROMPT_TEMPLATES

# This module contains all prompt templates for different agent types
PROMPT_TEMPLATES = {
    **TOOL_CALLING_PROMPT_TEMPLATES,
    **FINAGENT_PROMPT_TEMPLATES,
    **SIMPLE_CHAT_PROMPT_TEMPLATES,
    **DEBATE_CHAT_PROMPT_TEMPLATES,
    **TRADING_OFFLINE_PROMPT_TEMPLATES
}