from .tool_calling import PROMPT_TEMPLATES as TOOL_CALLING_PROMPT_TEMPLATES
from .interactive import PROMPT_TEMPLATES as INTERACTIVE_PROMPT_TEMPLATES
from .finagent import PROMPT_TEMPLATES as FINAGENT_PROMPT_TEMPLATES

# This module contains all prompt templates for different agent types
PROMPT_TEMPLATES = {
    **TOOL_CALLING_PROMPT_TEMPLATES,
    **INTERACTIVE_PROMPT_TEMPLATES,
    **FINAGENT_PROMPT_TEMPLATES
}