from .tool_calling import PROMPT_TEMPLATES as TOOL_CALLING_PROMPT_TEMPLATES
from .simple_chat import PROMPT_TEMPLATES as SIMPLE_CHAT_PROMPT_TEMPLATES
from .debate_chat import PROMPT_TEMPLATES as DEBATE_CHAT_PROMPT_TEMPLATES
from .interday_trading import PROMPT_TEMPLATES as INTERDAY_TRADING_PROMPT_TEMPLATES
from .intraday_trading import PROMPT_TEMPLATES as INTRADAY_TRADING_PROMPT_TEMPLATES
from .operator_browser import PROMPT_TEMPLATES as OPERATOR_BROWSER_PROMPT_TEMPLATES
from .mobile import PROMPT_TEMPLATES as MOBILE_PROMPT_TEMPLATES
from .anthropic_mobile import PROMPT_TEMPLATES as ANTHROPIC_MOBILE_PROMPT_TEMPLATES

# This module contains all prompt templates for different agent types
PROMPT_TEMPLATES = {
    **TOOL_CALLING_PROMPT_TEMPLATES,
    **SIMPLE_CHAT_PROMPT_TEMPLATES,
    **DEBATE_CHAT_PROMPT_TEMPLATES,
    **INTERDAY_TRADING_PROMPT_TEMPLATES,
    **INTRADAY_TRADING_PROMPT_TEMPLATES,
    **OPERATOR_BROWSER_PROMPT_TEMPLATES,
    **MOBILE_PROMPT_TEMPLATES,
    **ANTHROPIC_MOBILE_PROMPT_TEMPLATES
}