"""Report Tool - A tool for managing ESG analysis reports with structured sections and content."""

import os
import json
from datetime import datetime
from typing import Optional, List, Dict, Any, Literal
from pydantic import Field, ConfigDict

from src.registry import TOOL
from src.logger import logger
from src.utils import assemble_project_path
from src.tool.types import Tool, ToolResponse


_REPORT_DESCRIPTION = """Report tool that manages ESG analysis reports with structured sections.

🎯 BEST FOR: Creating and managing structured ESG analysis reports:
- Initialize a new report with ESG template
- Add/update report sections (Executive Summary, Data Analysis, Findings, etc.)
- Add data tables in markdown format
- Add images/charts with captions
- Track report completion status
- Finalize and export the report

💡 Use this tool for:
- Creating structured ESG analysis reports
- Organizing findings from retriever and plotter tools
- Building reports incrementally across multiple steps
- Adding charts, tables, and text to reports
- Generating final report.md files

📋 Available actions:
- init: Initialize a new report
- add_section: Add or update a section
- add_table: Add a data table to a section
- add_image: Add an image/chart reference
- add_finding: Add a key finding or insight
- get_status: Get current report structure and completion status
- finalize: Generate the final report.md file
"""

# ESG Report Template
ESG_REPORT_TEMPLATE = """# {title}

**Generated:** {date}
**Task:** {task_description}

---

## Executive Summary

{executive_summary}

---

## Table of Contents

{toc}

---

{sections}

---

## Key Findings

{findings}

---

## Appendix

### Data Sources
{data_sources}

### Charts and Visualizations
{charts}

---

*Report generated by ESG Agent*
"""


@TOOL.register_module(force=True)
class ReportTool(Tool):
    """A tool that manages ESG analysis reports with structured sections."""
    model_config = ConfigDict(arbitrary_types_allowed=True, extra="allow")

    name: str = "report"
    description: str = _REPORT_DESCRIPTION
    enabled: bool = True

    # Configuration parameters
    base_dir: str = Field(
        default=None,
        description="The base directory for saving reports."
    )
    
    # Report state (not persisted, managed per session)
    _report_state: Dict[str, Any] = {}

    def __init__(self, base_dir: Optional[str] = None, **kwargs):
        """Initialize the report tool."""
        super().__init__(**kwargs)
        
        if base_dir is not None:
            self.base_dir = assemble_project_path(base_dir)
            
        if self.base_dir is not None:
            os.makedirs(self.base_dir, exist_ok=True)
        
        # Initialize empty report state
        self._report_state = {}

    def _get_default_state(self, title: str, task_description: str) -> Dict[str, Any]:
        """Get default report state structure."""
        return {
            "title": title,
            "task_description": task_description,
            "created_at": datetime.now().isoformat(),
            "updated_at": datetime.now().isoformat(),
            "status": "in_progress",
            "executive_summary": "",
            "sections": {},  # section_name -> content
            "section_order": [],  # ordered list of section names
            "tables": {},  # section_name -> list of tables
            "images": [],  # list of {path, caption, section}
            "findings": [],  # list of key findings
            "data_sources": [],  # list of data sources referenced
        }

    def _update_timestamp(self):
        """Update the last modified timestamp."""
        if self._report_state:
            self._report_state["updated_at"] = datetime.now().isoformat()

    def _save_state(self):
        """Save report state to JSON file."""
        if self._report_state and self.base_dir:
            state_path = os.path.join(self.base_dir, "report_state.json")
            with open(state_path, 'w', encoding='utf-8') as f:
                json.dump(self._report_state, f, indent=2, ensure_ascii=False)
            logger.info(f"| 💾 Report state saved to {state_path}")

    def _load_state(self) -> bool:
        """Load report state from JSON file if exists."""
        if self.base_dir:
            state_path = os.path.join(self.base_dir, "report_state.json")
            if os.path.exists(state_path):
                with open(state_path, 'r', encoding='utf-8') as f:
                    self._report_state = json.load(f)
                logger.info(f"| 📂 Report state loaded from {state_path}")
                return True
        return False

    def _generate_toc(self) -> str:
        """Generate table of contents from sections."""
        if not self._report_state.get("section_order"):
            return "*No sections added yet*"
        
        toc_lines = []
        for i, section_name in enumerate(self._report_state["section_order"], 1):
            # Create anchor link
            anchor = section_name.lower().replace(" ", "-").replace(":", "")
            toc_lines.append(f"{i}. [{section_name}](#{anchor})")
        
        return "\n".join(toc_lines)

    def _generate_sections_content(self) -> str:
        """Generate all sections content."""
        if not self._report_state.get("section_order"):
            return "*No sections added yet*"
        
        sections_content = []
        for section_name in self._report_state["section_order"]:
            section_text = f"## {section_name}\n\n"
            
            # Add section content
            content = self._report_state["sections"].get(section_name, "")
            if content:
                section_text += content + "\n\n"
            
            # Add tables for this section
            tables = self._report_state["tables"].get(section_name, [])
            for table in tables:
                section_text += table + "\n\n"
            
            # Add images for this section
            for img in self._report_state["images"]:
                if img.get("section") == section_name:
                    section_text += f"![{img['caption']}]({img['path']})\n\n"
                    section_text += f"*{img['caption']}*\n\n"
            
            sections_content.append(section_text)
        
        return "\n---\n\n".join(sections_content)

    def _generate_findings_content(self) -> str:
        """Generate key findings content."""
        if not self._report_state.get("findings"):
            return "*No key findings added yet*"
        
        findings_lines = []
        for i, finding in enumerate(self._report_state["findings"], 1):
            findings_lines.append(f"{i}. {finding}")
        
        return "\n".join(findings_lines)

    def _generate_data_sources_content(self) -> str:
        """Generate data sources content."""
        if not self._report_state.get("data_sources"):
            return "*No data sources referenced*"
        
        sources = list(set(self._report_state["data_sources"]))  # Remove duplicates
        return "\n".join([f"- {source}" for source in sources])

    def _generate_charts_content(self) -> str:
        """Generate charts appendix content."""
        if not self._report_state.get("images"):
            return "*No charts added*"
        
        charts_lines = []
        for i, img in enumerate(self._report_state["images"], 1):
            charts_lines.append(f"{i}. **{img['caption']}** - `{img['path']}`")
        
        return "\n".join(charts_lines)

    def _generate_report_markdown(self) -> str:
        """Generate the full report markdown."""
        return ESG_REPORT_TEMPLATE.format(
            title=self._report_state.get("title", "ESG Analysis Report"),
            date=datetime.now().strftime("%Y-%m-%d %H:%M"),
            task_description=self._report_state.get("task_description", ""),
            executive_summary=self._report_state.get("executive_summary", "*No executive summary provided*"),
            toc=self._generate_toc(),
            sections=self._generate_sections_content(),
            findings=self._generate_findings_content(),
            data_sources=self._generate_data_sources_content(),
            charts=self._generate_charts_content(),
        )

    async def __call__(
        self,
        action: Literal["init", "add_section", "add_table", "add_image", "add_finding", "get_status", "finalize"],
        title: Optional[str] = None,
        task_description: Optional[str] = None,
        section_name: Optional[str] = None,
        content: Optional[str] = None,
        table_markdown: Optional[str] = None,
        image_path: Optional[str] = None,
        image_caption: Optional[str] = None,
        finding: Optional[str] = None,
        data_source: Optional[str] = None,
        output_filename: Optional[str] = None,
        **kwargs
    ) -> ToolResponse:
        """Execute report management action.

        Args:
            action: The action to perform:
                - "init": Initialize a new report (requires title, task_description)
                - "add_section": Add or update a section (requires section_name, content)
                - "add_table": Add a table to a section (requires section_name, table_markdown)
                - "add_image": Add an image reference (requires section_name, image_path, image_caption)
                - "add_finding": Add a key finding (requires finding)
                - "get_status": Get current report status
                - "finalize": Generate and save the final report.md
            title: Report title (for init action)
            task_description: Task description (for init action)
            section_name: Section name (for add_section, add_table, add_image)
            content: Section content (for add_section)
            table_markdown: Markdown table string (for add_table)
            image_path: Path to image file (for add_image)
            image_caption: Caption for image (for add_image)
            finding: Key finding text (for add_finding)
            data_source: Data source reference to add
            output_filename: Custom output filename (for finalize, default: report.md)
        """
        try:
            logger.info(f"| 📝 ReportTool action: {action}")

            # Try to load existing state if not initialized
            if not self._report_state:
                self._load_state()

            if action == "init":
                # Initialize a new report
                if not title:
                    title = "ESG Analysis Report"
                if not task_description:
                    task_description = "ESG data analysis and report generation"
                
                self._report_state = self._get_default_state(title, task_description)
                self._save_state()
                
                logger.info(f"| ✅ Report initialized: {title}")
                return ToolResponse(
                    success=True,
                    message=f"Report initialized successfully!\n\nTitle: {title}\nTask: {task_description}\n\nYou can now add sections, tables, images, and findings.",
                    extra={"title": title, "status": "in_progress"}
                )

            elif action == "add_section":
                # Add or update a section
                if not self._report_state:
                    return ToolResponse(
                        success=False,
                        message="Report not initialized. Please call 'init' action first."
                    )
                
                if not section_name:
                    return ToolResponse(
                        success=False,
                        message="section_name is required for add_section action."
                    )
                
                # Add to section order if new
                if section_name not in self._report_state["section_order"]:
                    self._report_state["section_order"].append(section_name)
                
                # Set or update content
                if content:
                    existing = self._report_state["sections"].get(section_name, "")
                    if existing:
                        # Append to existing content
                        self._report_state["sections"][section_name] = existing + "\n\n" + content
                    else:
                        self._report_state["sections"][section_name] = content
                else:
                    if section_name not in self._report_state["sections"]:
                        self._report_state["sections"][section_name] = ""
                
                # Handle executive summary specially
                if section_name.lower() == "executive summary" and content:
                    self._report_state["executive_summary"] = content
                
                # Add data source if provided
                if data_source:
                    self._report_state["data_sources"].append(data_source)
                
                self._update_timestamp()
                self._save_state()
                
                logger.info(f"| ✅ Section added/updated: {section_name}")
                return ToolResponse(
                    success=True,
                    message=f"Section '{section_name}' added/updated successfully!\n\nCurrent sections: {', '.join(self._report_state['section_order'])}",
                    extra={"section_name": section_name, "sections": self._report_state["section_order"]}
                )

            elif action == "add_table":
                # Add a table to a section
                if not self._report_state:
                    return ToolResponse(
                        success=False,
                        message="Report not initialized. Please call 'init' action first."
                    )
                
                if not section_name or not table_markdown:
                    return ToolResponse(
                        success=False,
                        message="section_name and table_markdown are required for add_table action."
                    )
                
                # Ensure section exists
                if section_name not in self._report_state["section_order"]:
                    self._report_state["section_order"].append(section_name)
                    self._report_state["sections"][section_name] = ""
                
                # Add table to section
                if section_name not in self._report_state["tables"]:
                    self._report_state["tables"][section_name] = []
                self._report_state["tables"][section_name].append(table_markdown)
                
                # Add data source if provided
                if data_source:
                    self._report_state["data_sources"].append(data_source)
                
                self._update_timestamp()
                self._save_state()
                
                logger.info(f"| ✅ Table added to section: {section_name}")
                return ToolResponse(
                    success=True,
                    message=f"Table added to section '{section_name}' successfully!",
                    extra={"section_name": section_name}
                )

            elif action == "add_image":
                # Add an image reference
                if not self._report_state:
                    return ToolResponse(
                        success=False,
                        message="Report not initialized. Please call 'init' action first."
                    )
                
                if not image_path or not image_caption:
                    return ToolResponse(
                        success=False,
                        message="image_path and image_caption are required for add_image action."
                    )
                
                # Use section_name or default to "Charts and Analysis"
                target_section = section_name or "Charts and Analysis"
                
                # Ensure section exists
                if target_section not in self._report_state["section_order"]:
                    self._report_state["section_order"].append(target_section)
                    self._report_state["sections"][target_section] = ""
                
                # Add image reference
                self._report_state["images"].append({
                    "path": image_path,
                    "caption": image_caption,
                    "section": target_section
                })
                
                self._update_timestamp()
                self._save_state()
                
                logger.info(f"| ✅ Image added: {image_caption}")
                return ToolResponse(
                    success=True,
                    message=f"Image added successfully!\n\nPath: {image_path}\nCaption: {image_caption}\nSection: {target_section}",
                    extra={"image_path": image_path, "section": target_section}
                )

            elif action == "add_finding":
                # Add a key finding
                if not self._report_state:
                    return ToolResponse(
                        success=False,
                        message="Report not initialized. Please call 'init' action first."
                    )
                
                if not finding:
                    return ToolResponse(
                        success=False,
                        message="finding is required for add_finding action."
                    )
                
                self._report_state["findings"].append(finding)
                
                # Add data source if provided
                if data_source:
                    self._report_state["data_sources"].append(data_source)
                
                self._update_timestamp()
                self._save_state()
                
                logger.info(f"| ✅ Finding added: {finding[:50]}...")
                return ToolResponse(
                    success=True,
                    message=f"Finding added successfully!\n\nTotal findings: {len(self._report_state['findings'])}",
                    extra={"finding": finding, "total_findings": len(self._report_state["findings"])}
                )

            elif action == "get_status":
                # Get current report status
                if not self._report_state:
                    return ToolResponse(
                        success=True,
                        message="No report initialized. Use 'init' action to create a new report.",
                        extra={"status": "not_initialized"}
                    )
                
                status_info = {
                    "title": self._report_state.get("title"),
                    "status": self._report_state.get("status"),
                    "created_at": self._report_state.get("created_at"),
                    "updated_at": self._report_state.get("updated_at"),
                    "sections": self._report_state.get("section_order", []),
                    "num_tables": sum(len(tables) for tables in self._report_state.get("tables", {}).values()),
                    "num_images": len(self._report_state.get("images", [])),
                    "num_findings": len(self._report_state.get("findings", [])),
                    "has_executive_summary": bool(self._report_state.get("executive_summary")),
                }
                
                status_text = f"""Report Status:
                
Title: {status_info['title']}
Status: {status_info['status']}
Created: {status_info['created_at']}
Last Updated: {status_info['updated_at']}

Sections ({len(status_info['sections'])}): {', '.join(status_info['sections']) if status_info['sections'] else 'None'}
Tables: {status_info['num_tables']}
Images: {status_info['num_images']}
Key Findings: {status_info['num_findings']}
Executive Summary: {'Yes' if status_info['has_executive_summary'] else 'No'}
"""
                
                logger.info(f"| 📊 Report status retrieved")
                return ToolResponse(
                    success=True,
                    message=status_text,
                    extra=status_info
                )

            elif action == "finalize":
                # Generate and save the final report
                if not self._report_state:
                    return ToolResponse(
                        success=False,
                        message="Report not initialized. Please call 'init' action first."
                    )
                
                # Generate report markdown
                report_content = self._generate_report_markdown()
                
                # Determine output path
                if output_filename:
                    if not output_filename.endswith('.md'):
                        output_filename += '.md'
                else:
                    output_filename = "report.md"
                
                output_path = os.path.join(self.base_dir, output_filename)
                
                # Save report
                with open(output_path, 'w', encoding='utf-8') as f:
                    f.write(report_content)
                
                # Update status
                self._report_state["status"] = "completed"
                self._update_timestamp()
                self._save_state()
                
                logger.info(f"| ✅ Report finalized: {output_path}")
                return ToolResponse(
                    success=True,
                    message=f"Report finalized and saved successfully!\n\nOutput file: {output_path}\n\nThe report includes:\n- {len(self._report_state['section_order'])} sections\n- {sum(len(t) for t in self._report_state['tables'].values())} tables\n- {len(self._report_state['images'])} images\n- {len(self._report_state['findings'])} key findings",
                    extra={"output_path": output_path, "status": "completed"}
                )

            else:
                return ToolResponse(
                    success=False,
                    message=f"Unknown action: {action}. Valid actions: init, add_section, add_table, add_image, add_finding, get_status, finalize"
                )

        except Exception as e:
            logger.error(f"| ❌ Error in ReportTool: {e}")
            import traceback
            return ToolResponse(
                success=False,
                message=f"Error in report action '{action}': {str(e)}\n{traceback.format_exc()}"
            )

